apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: crypto
  name: crypto
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: crypto
    spec:
      containers:
      - image: gcr.io/cryptoextractor-257309/crypto
        name: crypto
        ports:
        - containerPort: 10010
        resources: {}
      restartPolicy: Always
status: {}
